/**
 * `gw golden` — stage 12, and the only place the two kinds of verification meet
 * (Law 7).
 *
 * Everything up to here measured **fidelity**: does this look like the design?
 * That question is asked once, against a Figma export, and then it is over —
 * the design will change and the component will carry real data instead of the
 * mockup's copy.
 *
 * What gets frozen here is **regression**: a screenshot of the component
 * itself, which answers "did I break it?" and keeps answering it in CI forever.
 * Freezing the Figma export instead would produce a suite that fails every time
 * a designer nudges a frame.
 */

import { copyFileSync, existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import {
  activeRun, advance, loadConfig, loadState, paths, saveState,
  type Framework, type GridwrightConfig, type RunScore, type RunState,
} from '@gridwright/core'
import { ok, fail, info, warn, dim, bold, green, yellow } from '../ui.js'

export interface GoldenArgs {
  run?: string
  component?: string
  approve?: boolean
}

export function runGolden(root: string, args: GoldenArgs): void {
  const config = loadConfig(root)
  if (!config) fail('This project is not configured.', 'Run `gw init` first.')
  const run = args.run ? loadState(root, args.run) : activeRun(root)
  if (!run) fail('No open run.', 'Start one with `gw build "<figma-url>"`.')

  const score = run.stages.verify.output?.score as RunScore | undefined
  if (!score) {
    fail(
      `Run ${run.id} has not been verified.`,
      'Freezing a baseline from an unmeasured component pins whatever it happens to look\n' +
        'like right now, mistakes included. Run `gw verify` first.',
    )
  }

  const shots = config.verify.viewports
    .map((v) => ({ viewport: v.name, file: join(root, '.gridwright', 'verify', `${v.name}.png`) }))
    .filter((s) => existsSync(s.file))

  if (shots.length === 0) {
    fail('No screenshots to freeze.', 'Run `gw verify` — the baselines come from its renders.')
  }

  if (!args.approve) {
    console.log(bold(`Freeze ${run.name} as the regression baseline?`))
    console.log()
    console.log(`  score    ${score.passed ? green(`${score.total}%`) : yellow(`${score.total}%`)} on ${score.worstViewport}, threshold ${score.threshold}`)
    console.log(`  baseline ${shots.length} viewport${shots.length === 1 ? '' : 's'} → ${relative(root, paths.baselines(root))}/`)
    console.log(`  test     ${testPath(config, run.name)}`)
    console.log()

    if (!score.passed) {
      // Allowed, but never quietly: a baseline is what every future run is
      // compared against, so freezing a failing one makes the failure the
      // standard.
      warn(`This run is below threshold. Freezing it makes ${score.total}% the new normal.`)
      console.log(dim('  Everything after this is measured against it, including CI.\n'))
    }

    warn('This is a human gate (Law 5). Nothing has been written.')
    console.log(dim('  Approve with: gw golden --approve'))
    process.exitCode = 1
    return
  }

  const dir = paths.baselines(root)
  mkdirSync(dir, { recursive: true })
  const frozen: string[] = []
  for (const s of shots) {
    const dest = join(dir, `${run.name}-${s.viewport}.png`)
    copyFileSync(s.file, dest)
    frozen.push(relative(root, dest))
  }

  const test = writeRegressionTest(root, config, run)

  ok(`Baseline frozen — ${frozen.length} viewport${frozen.length === 1 ? '' : 's'}`)
  for (const f of frozen) console.log(`    ${dim('·')} ${f}`)
  if (test) console.log(`    ${dim('·')} ${test} ${dim('(new)')}`)
  console.log(dim('\n  These are committed, unlike runs/ and dashboard/ — they are test code.'))

  advance(run, 'golden', { status: 'done', output: { baselines: frozen, test } })
  saveState(root, run)
  info(`Now on ${green(run.stage)}`)
}

function testPath(config: GridwrightConfig, name: string): string {
  return join(config.library.dir, '__tests__', `${name}.regression.spec.ts`)
}

/**
 * Writes a Playwright spec — once. If one already exists it is left alone,
 * because by then it may have assertions nobody wants overwritten by a
 * generator.
 */
function writeRegressionTest(root: string, config: GridwrightConfig, run: RunState): string | null {
  const rel = testPath(config, run.name)
  const abs = join(root, rel)
  if (existsSync(abs)) return null

  mkdirSync(dirname(abs), { recursive: true })
  writeFileSync(abs, spec(config, run))
  return rel
}

function spec(config: GridwrightConfig, run: RunState): string {
  const viewports = config.verify.viewports
    .map((v) => `  { name: '${v.name}', width: ${v.width}, height: ${v.height} },`)
    .join('\n')

  return `import { test, expect } from '@playwright/test'

/**
 * Regression baseline for ${run.name} — generated by gridwright, then yours.
 *
 * This asks "did I break it?", not "does it match the design?". Fidelity to
 * Figma was checked once, when the component was built; the design will move on
 * and this must not fail because of it.
 *
 * Update the snapshots deliberately, with --update-snapshots, when a change to
 * the component is intended.
 */

const VIEWPORTS = [
${viewports}
]

for (const vp of VIEWPORTS) {
  test(\`${run.name} at \${vp.name}\`, async ({ page }) => {
    await page.setViewportSize({ width: vp.width, height: vp.height })
    // Point this at wherever the project renders components in isolation.
    await page.goto('/${run.name}')
    await page.evaluate(() => document.fonts.ready)

    await expect(page).toHaveScreenshot(\`${run.name}-\${vp.name}.png\`, {
      // Fonts and antialiasing differ between machines; the threshold absorbs
      // that without hiding a real layout change.
      maxDiffPixelRatio: 0.01,
    })
  })
}
`
}
