/**
 * `gw report` — stage 14, the dashboard.
 *
 * Static HTML with the images inlined, written into `.gridwright/dashboard/`.
 * No server and no build step: it has to still open in a browser months later,
 * from a directory that is gitignored, without anyone installing anything.
 *
 * The history at the bottom is the part that makes the system improve. One run
 * tells you whether a component worked; twenty runs tell you which metric
 * always fails — and that is a rule to add to the config, not a prompt to
 * tweak.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import {
  activeRun, advance, listRuns, loadConfig, loadState, paths, saveState,
  type IR, type RunScore, type RunState,
} from '@gridwright/core'
import type { Resolution } from '@gridwright/tokens'
import { ok, fail, info, dim, green } from '../ui.js'

export interface ReportArgs { run?: string; open?: boolean }

export function runReport(root: string, args: ReportArgs): void {
  const config = loadConfig(root)
  if (!config) fail('This project is not configured.', 'Run `gw init` first.')
  const run = args.run ? loadState(root, args.run) : activeRun(root)
  if (!run) fail('No run to report on.', 'Start one with `gw build "<figma-url>"`.')

  const dir = paths.dashboard(root)
  mkdirSync(dir, { recursive: true })
  const out = join(dir, 'index.html')
  writeFileSync(out, page(root, run, listRuns(root)))

  ok(`Dashboard written to ${out}`)
  console.log(dim('  Static HTML with the images inlined — it opens from disk, months from now.'))

  if (run.stage === 'report') {
    advance(run, 'report', { status: 'done', output: { file: out } })
    saveState(root, run)
    info(`Run ${run.id} complete.`)
  }
}

function page(root: string, run: RunState, all: RunState[]): string {
  const ir = readJson<IR>(paths.ir(root, run.id))
  const resolutions = readJson<Resolution[]>(paths.resolutions(root, run.id)) ?? []
  const score = run.stages.verify.output?.score as RunScore | undefined

  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<title>${esc(run.name)} — gridwright</title>
<style>
  :root { --ink:#1a1a1a; --muted:#6b6b6b; --line:#e6e3de; --bg:#fbfbfa;
          --ok:#16a34a; --warn:#d97706; --bad:#dc2626; --code:#2563eb; }
  * { box-sizing: border-box; }
  body { margin:0; padding:40px; background:var(--bg); color:var(--ink);
         font:14px/1.55 ui-sans-serif,-apple-system,Segoe UI,Roboto,sans-serif; }
  main { max-width:1100px; margin:0 auto; }
  h1 { font-size:22px; margin:0 0 4px; }
  h2 { font-size:15px; margin:36px 0 12px; padding-bottom:6px; border-bottom:1px solid var(--line); }
  .sub { color:var(--muted); margin-bottom:28px; }
  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(300px,1fr)); gap:16px; }
  .card { background:#fff; border:1px solid var(--line); border-radius:8px; padding:14px; }
  .card img { width:100%; border-radius:4px; border:1px solid var(--line); display:block; }
  .score { font-size:26px; font-weight:700; }
  .pass { color:var(--ok); } .fail { color:var(--bad); } .warn { color:var(--warn); }
  table { border-collapse:collapse; width:100%; }
  td, th { text-align:left; padding:6px 10px; border-bottom:1px solid var(--line); vertical-align:top; }
  th { color:var(--muted); font-weight:600; font-size:12px; text-transform:uppercase; letter-spacing:.04em; }
  code, pre { font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:12.5px; }
  pre { background:#fff; border:1px solid var(--line); border-radius:6px; padding:12px; overflow:auto; max-height:340px; }
  .tag { display:inline-block; padding:1px 7px; border-radius:999px; font-size:11px; font-weight:600; }
  .t-exact { background:#eef7f0; color:var(--ok); }
  .t-near  { background:#fdf4e7; color:var(--warn); }
  .t-new   { background:#eef3fd; color:var(--code); }
  .muted { color:var(--muted); }
  details summary { cursor:pointer; color:var(--muted); }
</style></head><body><main>

<h1>${esc(run.name)}</h1>
<div class="sub">run <code>${esc(run.id)}</code> · ${esc(run.mode)} · node <code>${esc(run.source.nodeId)}</code></div>

${scoreSection(root, run, score)}
${tokensSection(resolutions)}
${irSection(ir)}
${stagesSection(run)}
${historySection(all)}

<p class="muted" style="margin-top:40px">
  Generated by gridwright. Screenshots are inlined, so this file works on its own.
</p>
</main></body></html>`
}

function scoreSection(root: string, run: RunState, score?: RunScore): string {
  if (!score) return '<h2>Verification</h2><p class="muted">Not verified yet.</p>'

  const cards = score.viewports.map((v) => {
    const shot = inlineImage(join(root, '.gridwright', 'verify', `${v.viewport}.png`))
    const diff = inlineImage(join(root, '.gridwright', 'verify', `${v.viewport}-diff.png`))
    const cls = v.total >= score.threshold ? 'pass' : 'fail'
    const dims = v.dimensions.map((d) =>
      d.unavailable
        ? `<tr><td>${d.dimension}</td><td class="muted">not measured — ${esc(d.unavailable)}</td></tr>`
        : `<tr><td>${d.dimension}</td><td>${d.score}%</td></tr>`,
    ).join('')

    // Findings are the actionable part: what moved and by how much.
    const findings = v.dimensions.flatMap((d) => d.findings).slice(0, 8)
    const list = findings.length
      ? `<details><summary>${findings.length} findings</summary><table>${
          findings.map((f) => `<tr><td><code>${esc(f.path)}</code></td><td>${esc(f.edge)} ${f.delta > 0 ? '+' : ''}${f.delta}</td></tr>`).join('')
        }</table></details>`
      : ''

    return `<div class="card">
      <div class="score ${cls}">${v.total}%</div>
      <div class="muted" style="margin-bottom:10px">${esc(v.viewport)} · ${v.width}px</div>
      ${shot ? `<img src="${shot}" alt="render at ${esc(v.viewport)}">` : ''}
      ${diff ? `<img src="${diff}" alt="diff at ${esc(v.viewport)}" style="margin-top:8px">` : ''}
      <table style="margin-top:10px">${dims}</table>
      ${list}
    </div>`
  }).join('')

  const verdict = score.passed
    ? `<span class="pass">passed</span>`
    : `<span class="fail">below threshold</span>`

  return `<h2>Verification</h2>
    <p>${verdict} — <strong>${score.total}%</strong> on ${esc(score.worstViewport)},
    threshold ${score.threshold}. <span class="muted">The worst viewport decides, never the average.</span></p>
    <div class="grid">${cards}</div>`
}

function tokensSection(resolutions: Resolution[]): string {
  if (resolutions.length === 0) return ''
  const rows = resolutions.map((r) => `<tr>
      <td><span class="tag t-${r.bucket}">${r.bucket}</span></td>
      <td><code>${esc(r.raw.value)}</code></td>
      <td>${r.match ? `<code>${esc(r.match.name)}</code>` : '<span class="muted">—</span>'}</td>
      <td class="muted">${esc(r.note ?? '')}</td>
    </tr>`).join('')

  return `<h2>Tokens</h2>
    <table><tr><th>bucket</th><th>design value</th><th>system token</th><th>note</th></tr>${rows}</table>
    <p class="muted">Anything marked <span class="tag t-near">near</span> used the system's value.
    That drift is the design system being defended, and it is on the record here.</p>`
}

function irSection(ir: IR | null): string {
  if (!ir) return ''
  const warnings = ir.warnings.length
    ? `<table>${ir.warnings.slice(0, 12).map((w) =>
        `<tr><td>${esc(w.severity)}</td><td>${esc(w.message)}</td></tr>`).join('')}</table>`
    : '<p class="muted">No warnings.</p>'

  return `<h2>The IR</h2>
    <p class="muted">hash <code>${esc(ir.hash)}</code> — the same design distills to the same hash,
    which is how a re-run is recognised as an update rather than a second component.</p>
    ${warnings}
    <details><summary>Full IR</summary><pre>${esc(JSON.stringify(ir, null, 2))}</pre></details>`
}

function stagesSection(run: RunState): string {
  const rows = Object.entries(run.stages)
    .filter(([, s]) => s.status !== 'pending')
    .map(([name, s]) => `<tr>
      <td><code>${esc(name)}</code></td>
      <td>${esc(s.status)}</td>
      <td class="muted">${esc(s.reason ?? '')}</td>
    </tr>`).join('')
  return `<h2>Stages</h2><table>${rows || '<tr><td class="muted">Nothing run yet.</td></tr>'}</table>`
}

/**
 * The part that compounds. One run says whether a component worked; twenty say
 * which metric always fails, and that is a rule for the config rather than a
 * prompt to tweak.
 */
function historySection(all: RunState[]): string {
  if (all.length < 2) return ''
  const rows = all.slice(0, 15).map((r) => {
    const score = (r.stages.verify.output?.score as RunScore | undefined)?.total
    const iterations = r.stages.refine.output?.iterations ?? 0
    return `<tr>
      <td><code>${esc(r.id)}</code></td>
      <td>${esc(r.name)}</td>
      <td>${score !== undefined ? `${score}%` : '<span class="muted">—</span>'}</td>
      <td>${iterations || '<span class="muted">0</span>'}</td>
      <td class="muted">${esc(r.stage)}</td>
    </tr>`
  }).join('')

  return `<h2>History</h2>
    <table><tr><th>run</th><th>component</th><th>score</th><th>refines</th><th>stage</th></tr>${rows}</table>
    <p class="muted">If the same dimension keeps failing across runs, that is a rule to add to
    <code>gridwright.config.json</code> — not a prompt to reword.</p>`
}

function inlineImage(path: string): string | null {
  if (!existsSync(path)) return null
  return `data:image/png;base64,${readFileSync(path).toString('base64')}`
}

function readJson<T>(path: string): T | null {
  if (!existsSync(path)) return null
  try {
    return JSON.parse(readFileSync(path, 'utf8')) as T
  } catch {
    return null
  }
}

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!)
}
